### ISSUE TITLE
Improve Code Climate maintainability rating to A

### ISSUE THREAD

**Issue by cygnan** [cygnan/twitter-wordcloud-bot#20]
### Methods
- [x] certify (c633e642a4ac3f643cc5404c4cc72ba1f0e55dce)
- [x] skip tweets (#21, #49)
- [x] search tweets (#29, #44, #49)
- [x] reply (#22, #35, #49, #61)
- [x] get_surfaces (#36)
- [x] get_words_frequencies (#36, #39)
- [x] generate a wordcloud image (#38, #61)
- [x] main (#49)

### Classes
- [x] Frequencies (#36)
- [x] TweetHandler (#68)

### Modules
- [x] logger.py (#63)
- [x] tweepy_handler.py (#65)
- [x] mecab.py (#66, #67)
- [x] wordcloud_handler.py (#66, #67)

### Others
- [x] block nesting (#40)
